development:
  port: 8080
  directory: ./
  database: ./ota.sql
  builds: ./builds
  templates: ./views

production:
  port: 8080
  directory: /var/lib/android_ota_server
  database: /var/lib/android_ota_server/ota.sql
  builds: /var/lib/android_ota_server/builds
  templates: /var/lib/android_ota_server/views
